# => experiment options
DEBUG: True
brute_force: True
EXP_NAME: '6P, 80deg, F/2.0, 7.66mm sensor, lens design'
seed: 1

# Modify the following parameters if you want to design you own lens
# ==================
# Design spec
HFOV: 0.7 # half diagonal FoV in radian
FNUM: 2.0 # F-number
DIAG: 7.66  # sensor diagonal length in mm
element: 6  # lens element number
# ==================

curriculum_steps: 5 # number of intermediate steps
FNUM_START: 2.8
DIAG_START: 4

# Learning rate
lrs: [5e-4, 1e-4, 1e-1, 1e-4]
ai_lr_decay: 0.1

# Random initialization
ai_degree: 6
flange: 1.2
rff: 0.9
d_aper: 0.2